name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: write-all
jobs:
  build:
    name: Build and Test Library
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
        versionSpec: '6.4.x'

    - name: Determine Version
      id: version_step # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v4
      with:
        updateProjectFiles: true

    # Regular unit tests (EXCLUDE integration)
    - name: Unit tests
      run: |
        cd src
        dotnet test --filter "TestCategory!=Integration" --coverage --report-trx

    - name: Build
      run: |
        cd src
        dotnet build -c Release

    - name: Unit Test Annotations
      run: |
        cd src
        dotnet tool update -g dotnet-Coverage
        dotnet tool update -g dotnet-reportgenerator-globaltool
        dotnet-coverage merge **\*.coverage --remove-input-files --output-format xml --output output.xml
        reportgenerator -reports:"output.xml" -targetdir:"output" -reporttypes:"MarkdownSummaryGithub"
        echo "### Test Results" >> "$env:GITHUB_STEP_SUMMARY"
        Get-ChildItem -Recurse -Filter *.trx | ForEach-Object {get-content $_.FullName | select-string 'executed=\"(\d+)\" passed=\"(\d+)\" failed=\"(\d+)\"' | ForEach-Object {":purple_circle: Tests: " + $_.Matches[0].Groups[1].Value + " :green_circle: Passed: " + $_.Matches[0].Groups[2].Value + " :red_circle: Failed: " + $_.Matches[0].Groups[3].Value}} >> "$env:GITHUB_STEP_SUMMARY"
        echo "### Code Coverage" >> "$env:GITHUB_STEP_SUMMARY"
        get-content output\SummaryGithub.md | select-string '<summary>(.+%)</summary>' | ForEach-Object {$_.Matches[0].Groups[1].Value} >> "$env:GITHUB_STEP_SUMMARY"

    - name: Documentation
      run: |
        dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github-packages "https://nuget.pkg.github.com/dotnet/index.json"
        dotnet tool update -g docfx --add-source github-packages --prerelease
        docfx docs/docfx.json

    - name: Upload Docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/_site

    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: src\**\bin\Release\*.nupkg

    - name: Create Zip for Release
      run: |
        $tempDir = New-Item -ItemType Directory -Path (Join-Path $env:TEMP ([System.Guid]::NewGuid()))
        Get-ChildItem -Path src -Recurse -Filter *.nupkg | Where-Object { $_.FullName -like '*\bin\release\*' } | ForEach-Object { Copy-Item $_.FullName -Destination $tempDir }
        Compress-Archive -Path $tempDir\* -Destination (Join-Path $env:GITHUB_WORKSPACE 'package.zip') -Force
        Remove-Item $tempDir -Recurse -Force

    - name: Test output
      run: echo ${{ steps.version_step.outputs.fullSemVer }}     

    - name: Create release
      if: ${{ github.event_name == 'push' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating release"
        echo gh release create --generate-notes v${{ steps.version_step.outputs.fullSemVer }} package.zip
        gh release create -t ${{ steps.version_step.outputs.fullSemVer }} --generate-notes v${{ steps.version_step.outputs.fullSemVer }} package.zip#package

    - name: Publish package
      if: ${{ github.event_name == 'push' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Adding local repo as nuget source"
        dotnet nuget add source --username tudormobile --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/tudormobile/index.json"
        echo "Pushing package"
        Get-ChildItem -Path src -Recurse -Filter *.nupkg | Where-Object { $_.FullName -like '*\bin\release\*' } | ForEach-Object {
          Write-Host "Pushing $($_.FullName)" 
          dotnet nuget push $_.FullName --source "github" --skip-duplicate 
          dotnet nuget push $_.FullName --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }}
        }
